// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3gwq8nc0mfOmd6Ybm675xtW-H4CwbL8w',
    appId: '1:726943186353:web:bd60c5b1b088be0921d190',
    messagingSenderId: '726943186353',
    projectId: 'todos-app-drk',
    authDomain: 'todos-app-drk.firebaseapp.com',
    storageBucket: 'todos-app-drk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRJdWFsFumT0-p8S6zW8-zBATgWrc7HC0',
    appId: '1:726943186353:android:9772461d0fe40a1c21d190',
    messagingSenderId: '726943186353',
    projectId: 'todos-app-drk',
    storageBucket: 'todos-app-drk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB27AiY5oI6scEOSQfMeQ213brP5GeIzZE',
    appId: '1:726943186353:ios:26b85bbb8b0190f221d190',
    messagingSenderId: '726943186353',
    projectId: 'todos-app-drk',
    storageBucket: 'todos-app-drk.appspot.com',
    iosClientId: '726943186353-3n9galtn53gj5vg8u6lcjjnd9ecdk818.apps.googleusercontent.com',
    iosBundleId: 'com.example.todosApp',
  );
}
